# 配置端口
server:
  # 模拟多个topic消费者的时候，注意需要修改相应的端口号
  port: 6667
#  port: 6668

spring:
  activemq:
    # 配置mq的服务器地址
    broker-url: "tcp://192.168.60.130:61616"
    # 访问的用户名和密码
    user: admin
    password: admin

  jms:
    # true代表topic的发布/订阅模式，false 代表队列，默认值为false
    pub-sub-domain: true


# 自定义队列名称

myTopic: boot-activemq-topic
